/*
 * ErrorHandling.h
 *
 * Description: Simple implementation of signal handlers. Include this and call RegisterErrorHandlers( ); in main( ) once.
 *
 *  Created on: Apr 26, 2010
 *      Author: loerwald
 */

#ifndef ERRORHANDLING_H_
#define ERRORHANDLING_H_

#ifndef WIN32

#include <execinfo.h>
#include <signal.h>

void leave( int sig );
void RegisterErrorHandlers( );

void RegisterErrorHandlers( )
{
    (void) signal( SIGABRT, leave );
    (void) signal( SIGFPE, leave );
    (void) signal( SIGILL, leave );
    (void) signal( SIGINT, leave );
    (void) signal( SIGSEGV, leave );
    (void) signal( SIGTERM, leave );
}

void leave(int sig)
{
	// Reset to defaults.
	signal(SIGABRT, SIG_DFL);
	signal(SIGFPE, SIG_DFL);
	signal(SIGILL, SIG_DFL);
	signal(SIGINT, SIG_DFL);
	signal(SIGSEGV, SIG_DFL);
	signal(SIGTERM, SIG_DFL);
	
	char * description = 0;
	char * sign = 0;
	
	switch(sig)
	{
		case SIGABRT:
			sign = "SIGABRT";
			description = "Abnormal termination, such as instigated by the abort function. (Abort.)";
			break;
		case SIGFPE:
			sign = "SIGFPE";
			description = "Erroneous arithmetic operation, such as divide by 0 or overflow. (Floating point exception.)";
			break;
		case SIGILL:
			sign = "SIGILL";
			description = "An ‘invalid object program’ has been detected. This usually means that there is an illegal instruction in the program. (Illegal instruction.)";
			break;
		case SIGINT:
			sign = "SIGINT";
			description = "Interactive attention signal; on interactive systems this is usually generated by typing some ‘break-in’ key at the terminal. (Interrupt.)";
			break;
		case SIGSEGV:
			sign = "SIGSEGV";
			description = "Invalid storage access; most frequently caused by attempting to store some value in an object pointed to by a bad pointer. (Segment violation.)";
			break;
		case SIGTERM:
			sign = "SIGTERM";
			description =  "Termination request made to the program. (Terminate.)";
			break;
		default:
			sign = "SIGUNK";
			description = "Unknown Exception!";
			break;
	}
	
	printf("\n\n"
		   "There was an exception of type \"%s\".\n"
		   "\"%s\".\n\n"
		   "Please excuse the inconvenience. You may want to report this error including the log.\n\n",
		   sign,
		   description );
	
	static const int nframes = 20;
	
	void *array[nframes];
	size_t size;
	char **strings;
	size_t i;
	
	size = backtrace (array, nframes);
	strings = backtrace_symbols (array, size);
	
	printf ("Obtained %zd stack frames.\n", size);
	
	for (i = 0; i < size; i++)
		printf ("%s\n", strings[i]);
	
	printf("\n");
	
	free (strings);
	
	exit(sig);
}

#else

void RegisterErrorHandlers()
{
	//! \todo Add error handling for windows.
}

#endif

#endif